// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeTasker/kubeTasker/pkg/client/clientset/versioned/typed/workflow/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeTaskerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKubeTaskerV1alpha1) Workflows(namespace string) v1alpha1.WorkflowInterface {
	return &FakeWorkflows{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeTaskerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
